### ISSUE TITLE
gensim - read bin file? 

### ISSUE THREAD

**Issue by deakkon** [ncbi-nlp/BioSentVec#12]
Hi everyone, 

thank you for making this resource public; it is a great help to the community. 

I am having issues loading the .bin (model) file with gensim. Code snippet follows:

from gensim.models.fasttext import *
gensim_fasttext_model = load_facebook_vectors(root_path+"models/pretrained/BioWordVec_PubMed_MIMICIII_d200.bin")

Although the above snippet uses CPU/RAM resources, it never loads the model (seems it is constantly loading) nor does it produce an error. 

When I try to load it with the fastText library, it loads it within 90ish seconds. Code snippet:

import fastText as fasttext
fasttext.load_model(root_path+'models/pretrained/BioWordVec_PubMed_MIMICIII_d200.bin')

Unfortunatelly, I would prefer to use the gensim approach as it enables the __getitem__ to generate representations (e.g. model['word_to_represent']). 

I can load the vec.bin file (pretrained word-embedding mapping) with 
from gensim.models import KeyedVectors
model = KeyedVectors.load_word2vec_format('BioWordVec_PubMed_MIMICIII_d200.vec.bin', binary=True)

but that does not help me in my current pipeline (as its not dealing with OOVs). 

Could you provide any help/guidance what might be wrong? My env ist:

Linux-3.10.0-693.5.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0]
NumPy 1.16.2
SciPy 1.1.0
gensim 3.7.2
FAST_VERSION 1

**Comment by qingyu-qc** [comment]
Hey,

Thanks for the question.

You can use the following codes to get the vector of an OOV:

from gensim.models import FastText
model = FastText.load_fasttext_format('BioWordVec_PubMed_MIMICIII_d200.bin')
#an example of OOV:
print(model['testaaaabbxws'])

Thanks! We have also edited the wiki page accordingly.

**Comment by PhysicsBen** [comment]
I am having the exact same issue as above

> I am having issues loading the .bin (model) file with gensim. Code snippet follows:
>from gensim.models.fasttext import *
>gensim_fasttext_model = >load_facebook_vectors(root_path+"models/pretrained/BioWordVec_PubMed_MIMICIII_d200.bin")
>Although the above snippet uses CPU/RAM resources, it never loads the model (seems it is constantly >loading) nor does it produce an error.

windows server 2016
python 3.7.1
numpy 1.14.6
scipi 1.1.0
gensim 3.4.0

**Comment by qingyu-qc** [comment]
Hi,

Thanks for your query.

First, I'm not sure whether it is the same issue. As shown in the first post, KeyedVectors.load_word2vec_format was used for loading the fastText model via Gensim and errors were occurred. However, it should be FastText.load_fasttext_format as I replied. For your case, you have used load_facebook_vectors and there were no errors.

In addition, I just tried to reproduce using your codes and tested with the same example I used previously:

`emb = load_facebook_vectors('BioWordVec_PubMed_MIMICIII_d200.bin')`
`print(emb['testaaaabbxws'])`

The model was loaded successfully and it gave the vector without problems:

[ 0.435911   -0.07318366  0.62977225  0.26289284  0.03467882 -0.3141335
 -0.13259198  0.1091215   0.14628957 -0.36856368 -0.6635518   0.33551714
 -0.35648254  0.14584671 -0.2448305   0.16635747 -0.15117086 -0.21212731
  0.45592707 -0.2668562 ...]

The only difference is that I used gensim 3.7, but I do not think this makes a huge difference.
Thus, I suspect, depending on the computational resource, it may take a while to load the fastText model. As you may know, the fastText model is much larger than the fastText precomputed vectors because it stores all the character ngram related info. It is common that it takes much more time to load the model than the precomputed vectors.

One solution is that, in my opinion, you could load the model once and save all the vectors that you need in a file. Then you only need to load the saved file next time without loading the complete model.

Thanks!

**Comment by deakkon** [comment]
> Hey,
> 
> Thanks for the question.
> 
> You can use the following codes to get the vector of an OOV:
> 
> from gensim.models import FastText
> model = FastText.load_fasttext_format('BioWordVec_PubMed_MIMICIII_d200.bin')
> #an example of OOV:
> print(model['testaaaabbxws'])
> 
> Thanks! We have also edited the wiki page accordingly.

Thank you for the clarification. 

If you use the latest gensim (3.7.2), which I am, the code above works but still takes a looooong time to load and uses a loooooot of RAM (30ish minutes, and 60+ GBs, respectively). Especially compared with the FBs fastText lib load time, which is 90ish seconds and uses a few GBs of RAM. The other suggestion (load_facebook_vectors) behaves the same. As you can imagine, this is quite impractical when developing something. 

Additionally, using load_fast_text_format has been deprecated, as they switched to using either load_facebook_vectors or load_facebook_model (depending if you want to continue training the model or use it to generate embeddings). 

This seems to be a gensim issue; I have opened an [issue](https://github.com/RaRe-Technologies/gensim/issues/2468) on their github. Hopefully they'll be able to debug/solve this. 

Just out of curiosity, what is the infrastructure you are opening the model at (i.e. how much RAM) and how long/how much RAM does it take, if you have an idea, for each of the two proposed approaches?

**Comment by deakkon** [comment]
Additionally, there is some discussion about the produced embedding. See [here](https://github.com/RaRe-Technologies/gensim/issues/2468#issuecomment-489492320). Do the results make sense to you?

**Comment by qingyu-qc** [comment]
Hi,

Sorry for the late reply. I have tried both loading fastext model using gensim and fasttext library. It seems exceptionally slow to load the model using gensim. I suspect it could be because of an update of gensim? Using fasttext library to load the model only takes a few minutes:

import fasttext
def load_fasttext_model(file_path):
    embedding = fasttext.load_model(file_path) 

Thanks!
