### ISSUE TITLE
Unable to handle negation of sentences 

### ISSUE THREAD

**Issue by naeemrehmat** [ncbi-nlp/BioSentVec#21]
When I calculated similarity between "disease causing" and "not disease causing" using BioSentVec. It gave "1" , but I think it should give close to zer0. Kindly have a look at following:
```
from scipy.spatial import distance
sentence_vector1 = model.embed_sentence(preprocess_sentence("disease causing")  )
sentence_vector2 = model.embed_sentence(preprocess_sentence("not disease causing")  )
cosine_sim = 1 - distance.cosine(sentence_vector1, sentence_vector2)
print( cosine_sim )  # this will print 1
```

**Comment by qingyu-qc** [comment]
Hi,

First, the input is more like a phrase not in sentence structures. Sentence embeddings are not designed at phrase level. Second, to my knowledge, this is a common problem for embeddings to detect negations in an unsupervised manner. That is, you need to fine-tune them. You could follow https://arxiv.org/ftp/arxiv/papers/1911/1911.04211.pdf, which discusses a few supervised learning approaches so that models are trained to detect negations.

Close for now. Let us know if you have other questions. Thanks!
